/*
 * TestingJFrameWithMatisseInJDK14.java
 *
 * Created on 17 de Setembro de 2008, 10:38
 */

package exp.swing.frames;


import javax.swing.GroupLayout.Alignment;



/**
 *
 * @author  c2334
 */
public class TestingJFrameWithMatisseInJDK14 extends javax.swing.JFrame {

    /** Creates new form TestingJFrameWithMatisseInJDK14 */
    public TestingJFrameWithMatisseInJDK14() {
        initComponents();
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("jButton1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(Alignment.LEADING)
      .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(223, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(102, 102, 102))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(Alignment.LEADING)
      .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(151, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(126, 126, 126))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingJFrameWithMatisseInJDK14().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  // End of variables declaration//GEN-END:variables

}
