/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * <p>
 * Classname: exp.swing.jtogglebutton.MyJToggleBttTests
 * </p>
 *
 * <p>
 * Copyright: Copyright (c) 2011 Efacec Engenharia e Sistemas, S.A.
 * <br>
 * This software is the confidential and proprietary information of EFACEC Eng. Sistemas.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into EFACEC SE.
 * </p>
 * <p>
 * Company: EFACEC Eng. Sistemas
 * <br>
 * Rua Eng.º Frederico Ulrich ? Ap. 3078
 * <br>
 * 4471-907 Moreira da Maia
 * <br>
 * PORTUGAL
 * <br>
 * Tel: +351 22 940 2000
 * <br>
 * Fax: +351 22 948 5428
 * <br>
 * Web: www.efacec.pt
 * <br>
 * Email: te@efacec.pt
 * </p>
 */
package exp.swing.jtogglebutton;

import java.awt.BorderLayout;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 * <p>
 * Description:
 * </p>
 *
 * Created on Apr 10, 2015, 6:04:40 PM
 *
 * @author rUI vALE - {rui dot vale at efacec dot pt}
 * @version $Revision: 1.1 $
 */
public class MyJToggleBttTests extends javax.swing.JPanel {

  /** Creates new form MyJToggleBttTests */
  public MyJToggleBttTests() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jtb = new javax.swing.JToggleButton();
    jButton1 = new javax.swing.JButton();

    jtb.setText("toggle");
    jtb.setLabel("toggle");
    jtb.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jtbMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jtbMouseReleased(evt);
      }
    });

    jButton1.setText("butt");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jButton1MousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jButton1MouseReleased(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(127, 127, 127)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jButton1)
          .addComponent(jtb))
        .addContainerGap(210, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jtb)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addContainerGap(211, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
    // TODO add your handling code here:
    System.out.println("jButton1MouseReleased");
  }//GEN-LAST:event_jButton1MouseReleased

  private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
    // TODO add your handling code here:
    System.out.println("jButton1MousePressed");
  }//GEN-LAST:event_jButton1MousePressed

  private void jtbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMousePressed
    // TODO add your handling code here:

//    final MouseListener[] mls = jtb.getMouseListeners();
//    for (MouseListener ml : mls) {
//      jtb.removeMouseListener(ml);
//    }

    System.out.println("jToggleButton1MousePressed");

    jtb.setSelected(true);
////    jtb.setEnabled(false);


    final Thread thread = new Thread(() -> {
      try {
        Thread.sleep(2500);
      } catch (InterruptedException interruptedException) {
      }

//      for (MouseListener ml : mls) {
//        jtb.addMouseListener(ml);
//      }


      final boolean isSel = jtb.isSelected();
      System.out.println("jToggleButton1.isSelected()?"+isSel);

      if(isSel){
        synchronized(obj2Lock){
          try {
            obj2Lock.wait(10000);
          } catch (InterruptedException interruptedException) {
          }
          System.out.println("Pressed action will exit...");
        }
      }


      SwingUtilities.invokeLater(() -> {
        jtb.setSelected(false);
        jtb.setEnabled(true);
      });

      System.out.println("...ended the wait/pressed action.");
    }, "ThreadName");
    thread.setDaemon(true);
    thread.start();


  }//GEN-LAST:event_jtbMousePressed

  private final Object obj2Lock = new Object();

  private void jtbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMouseReleased
    // TODO add your handling code here:

    System.out.println("jToggleButton1MouseReleased");

    jtb.setSelected(false);
    jtb.setEnabled(false);

    final Thread thread = new Thread(() -> {

      synchronized(obj2Lock){
        System.out.println("Will notifyAll to wake up...");
        obj2Lock.notifyAll();
        System.out.println("...just notified all the waiting threads.");
      }


      try {
        // just to allow some breathing...
        Thread.sleep(1000);
      } catch (InterruptedException interruptedException) {
      }


      SwingUtilities.invokeLater(() -> {
        jtb.setSelected(false);
        jtb.setEnabled(true);
      });


      System.out.println("...ended the mouse released process.");

    }, "ThreadName");
    thread.setDaemon(true);
    thread.start();



  }//GEN-LAST:event_jtbMouseReleased


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JToggleButton jtb;
  // End of variables declaration//GEN-END:variables



  public static void main(String[] args) {
    MyJToggleBttTests m = new MyJToggleBttTests();
    JFrame f = new JFrame("sdkjskdsjk");
    f.setBounds(100,100,400,400);
    f.setLayout(new BorderLayout());
    f.add(m);
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setVisible(true);
  }
}
