/*
 * SimpleTabInsideTab.java
 *
 * Created on 10 de Julho de 2008, 18:52
 */

package jdk1_6examples.javax.swing.tabpane;

import javax.swing.JPanel;


/**
 *
 * @author  c2334
 */
public class SimpleTabInsideTab extends javax.swing.JFrame {

    /** Creates new form SimpleTabInsideTab */
    public SimpleTabInsideTab() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jTabbedPane2 = new javax.swing.JTabbedPane();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jTabbedPane3 = new javax.swing.JTabbedPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTabbedPane1.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N

    jPanel1.setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 287, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 131, Short.MAX_VALUE)
    );

    jTabbedPane2.addTab("Mod1 tab 1", jPanel3);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 287, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 131, Short.MAX_VALUE)
    );

    jTabbedPane2.addTab("Mod1 tab 2", jPanel4);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 287, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 131, Short.MAX_VALUE)
    );

    jTabbedPane2.addTab("Mod1 tab3", jPanel5);

    jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("CCTV", jPanel1);

    jPanel2.setLayout(new java.awt.BorderLayout());
    jTabbedPane1.addTab("PID Groups", jPanel2);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 292, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 156, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("PA Stops Groups", jPanel6);
    jTabbedPane1.addTab("PA Trams Groups", jTabbedPane3);

    getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             final SimpleTabInsideTab s = new SimpleTabInsideTab();
             s.setSize(250, 700);
             s.setVisible(true);
                
                
                /***
              new Thread(new Runnable(){
                public void run(){
                try {
                Thread.sleep(3000);
              } catch(Exception e) {
              }
                  System.out.println("waking up"); 

                  JPanel jp = new JPanel();
                  jp.setName("new TAB");
                  s.jTabbedPane1.add(jp);
                  s.validate();
                  s.repaint();
                  s.validate();
                  s.repaint();
                  
                }
              }).start();
              /**/
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTabbedPane jTabbedPane3;
  // End of variables declaration//GEN-END:variables

}
