/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * <p>
 * Classname:  jdk1_6examples.javax.swing.jpopupmenu.JProgressBarWithVariousStrings
 * </p>
 *
 * <p>Copyright: Copyright (c) 2009 Efacec Engenharia e Sistemas, S.A.
 * <br>
 * This software is the confidential and proprietary information of EFACEC Eng. Sistemas.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into EFACEC SE.
 * </p>
 * <p>Company: EFACEC Eng. Sistemas
 * <br>
 * Rua Eng.º Frederico Ulrich ? Ap. 3078
 * <br>
 * 4471-907 Moreira da Maia
 * <br>
 * PORTUGAL
 * <br>
 * Tel: +351 22 940 2000
 * <br>
 * Fax: +351 22 948 5428
 * <br>
 * Web: www.efacec.pt
 * <br>
 * Email: te@efacec.pt
 * </p>
 */

package jdk1_6examples.javax.swing.jpopupmenu;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 * <p>
 * Description:
 * </p>
 *
 * Created on 4/Jan/2011, 16:57:13
 *
 * @author rUI vALE - {rui dot vale at efacec dot pt}
 * @version $Revision: 1.1 $
 */
public class JProgressBarWithVariousStrings extends JPanel{

    /** Creates new form JProgressBarWithVariousStrings */
    public JProgressBarWithVariousStrings() {
        //initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables


  public static void main(String[] args) {

    SwingUtilities.invokeLater(new Runnable() {

      @Override
      public void run() {
        final JPanel jp = new JPanel();
        jp.setLayout(null);
        final MyJProgressBar m = new MyJProgressBar();
        jp.add(m);

        

        final javax.swing.JFrame f = new javax.swing.JFrame("burn files");
        f.setLayout(new java.awt.BorderLayout());
        f.add(jp, java.awt.BorderLayout.CENTER);
        //f.pack();
        f.setSize(550, 100);
        f.setDefaultCloseOperation( javax.swing.JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
      }
    });

  }
}

class MyJProgressBar extends JProgressBar{

  private static final double D_WIDTH_DIVIDER = 6.7;
  private static final double D_hEIGHT_DIVIDER = 1.4;

  MyJProgressBar(){
    setBounds(10,10,250,22);
  }

  @Override
  public void paint(Graphics g){
    super.paint(g);

    g.setColor(Color.red);
    g.drawString(
        "700",
        (int)(this.getWidth()/D_WIDTH_DIVIDER),
        (int)(this.getHeight()/D_hEIGHT_DIVIDER));
    g.setColor(Color.black);
    g.drawString(
        "4700",
        this.getWidth() - (int)(this.getWidth()/D_WIDTH_DIVIDER),
        (int)(this.getHeight()/D_hEIGHT_DIVIDER));
  }
}
