/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MouseButtonsTests.java
 *
 * Created on 10/Dez/2008, 15:41:29
 */

package jdk1_6examples.java.awt.event.mouse;

import java.awt.Component;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JPanel;


/**
 *
 * @author c2334
 */
public class MouseButtonsTests extends javax.swing.JFrame {

    /** Creates new form MouseButtonsTests */
    public MouseButtonsTests() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("click me");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton1MouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(76, 76, 76)
        .addComponent(jButton1)
        .addContainerGap(223, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(61, 61, 61)
        .addComponent(jButton1)
        .addContainerGap(216, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      // TODO add your handling code here:

      System.out.println("MouseEvent: modifiers:");

      if(evt.getModifiers() == MouseEvent.BUTTON1_MASK){
        System.out.println("evt.getModifiers() == MouseEvent.BUTTON1_MASK");
      }
      if(evt.getModifiers() == MouseEvent.BUTTON1_DOWN_MASK){
        System.out.println("evt.getModifiers() == MouseEvent.BUTTON1_DOWN_MASK");
      }
      if(evt.getButton() == MouseEvent.BUTTON1){
        System.out.println("evt.getButton() == MouseEvent.BUTTON1");
      }

      final MouseEvent me = new MouseEvent(
                    new java.awt.Label(),                            // source comp
                    -1,                                       // id
                    System.currentTimeMillis(),               // when
                    InputEvent.BUTTON1_MASK,                  // modifiers,
                    0,                                        // x
                    0,                                        // y
                    1,                                        // clickCount
                    false,                                    // popupTrigger
                    MouseEvent.BUTTON1);

      System.out.println("Mine own MouseEvent: modifiers:");

      if(me.getModifiers() == MouseEvent.BUTTON1_MASK){
        System.out.println("me.getModifiers() == MouseEvent.BUTTON1_MASK");
      }
      if(me.getModifiers() == MouseEvent.BUTTON1_DOWN_MASK){
        System.out.println("me.getModifiers() == MouseEvent.BUTTON1_DOWN_MASK");
      }
      if(me.getButton() == MouseEvent.BUTTON1){
        System.out.println("me.getButton() == MouseEvent.BUTTON1");
      }
      
    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseButtonsTests().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  // End of variables declaration//GEN-END:variables

}
