//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.08.20 at 03:34:05 PM PDT
//


package jdk1_6examples.xml.unmarshal;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry public class ObjectFactory {

  private final static QName _Item_QNAME = new QName("", "item");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
   *
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Item }
   *
   */
  public Item createItem() {
    return new Item();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "", name = "item")public JAXBElement<Item>
      createItem(Item value) {
    return new JAXBElement<Item> (_Item_QNAME, Item.class, null, value);
  }

}
