/**
 * <p>
 * Classname: exp.web.service.soap.client.Hello
 * </p>
 * <p>
 * <p>
 * Copyright: Copyright (c) 2015 Efacec Engenharia e Sistemas, S.A.
 * <br>
 * This software is the confidential and proprietary information of EFACEC Eng. Sistemas.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into EFACEC SE.
 * </p>
 * <p>
 * Company: EFACEC Eng. Sistemas
 * <br>
 * Rua Eng.º Frederico Ulrich ? Ap. 3078
 * <br>
 * 4471-907 Moreira da Maia
 * <br>
 * PORTUGAL
 * <br>
 * Tel: +351 22 940 2000
 * <br>
 * Fax: +351 22 948 5428
 * <br>
 * Web: www.efacec.pt
 * <br>
 * Email: te@efacec.pt
 * </p>
 */
package exp.web.service.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * <p>
 * This class was generated by the JAX-WS RI.
 * <p>
 * JAX-WS RI 2.1.6 in JDK 6
 * <p>
 * Generated source version: 2.1
 * <p>
 * <p>
 * <p>
 */

@WebService(name = "Hello", targetNamespace = "http://soap.service.web.exp/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Hello {

  /**
   *
   *
   *
   * @param arg0
   *
   * @return
   *
   *         returns java.lang.String
   *
   */
  @WebMethod
  @WebResult(partName = "return")
  public String sayHello(
      @WebParam(name = "arg0", partName = "arg0") String arg0);

}
