
/**
 * <p>
 * Classname: package tlc.radio.RadioTlcSpecUpperPanel
 * </p>
 *
 * <p>Copyright: Copyright (c) 2008 EFACEC SE
 * <br>
 * This software is the confidential and proprietary information of EFACEC SE.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into EFACEC SE.
 * </p>
 * <p>Company: EFACEC SE
 * <br>
 * Rua Engº Frederico Ulrich - Apartado 3081
 * <br>
 * 4471-907 Moreira da Maia
 * <br>
 * PORTUGAL
 * <br>
 * Tel.: +351 22 943 20 00
 * <br>
 * Fax: +351 22 943 20 50
 * <br>
 * Web: www.efacec.pt
 * <br>
 * Email: te@efacec.pt
 * </p>
 */

package tlc.radio;

import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * <p>
 * Description:
 * </p>
 *
 * @author rUI vALE - rui dot vale at efacec dot pt
 * @version $Revision: 1.1 $
 */
public class RadioTlcSpecUpperPanel extends javax.swing.JPanel {
  /** This class LOGGER */
  private static final Logger LOGGER =
    Logger.getLogger(RadioTlcSpecUpperPanel.class.getName());

 /**
  * The RadioTlcSpecUpperPanel default constuctor.
  */
  public RadioTlcSpecUpperPanel() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelEHP = new javax.swing.JPanel();
    jPanelEhpTable = new javax.swing.JPanel();
    jPanelEhpCalls = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jPanelEhpTableList = new javax.swing.JPanel();
    jScrollPaneEhpTableList = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanelEhpButtons = new javax.swing.JPanel();
    jToggleButtonConnect = new javax.swing.JToggleButton();
    jToggleButtonHangUp = new javax.swing.JToggleButton();
    jPanelEHP1 = new javax.swing.JPanel();
    jPanelEhpTable1 = new javax.swing.JPanel();
    jPanelEhpCalls1 = new javax.swing.JPanel();
    jTextField2 = new javax.swing.JTextField();
    jPanelEhpTableList1 = new javax.swing.JPanel();
    jScrollPaneEhpTableList1 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jPanelEhpButtons1 = new javax.swing.JPanel();
    jToggleButtonConnect1 = new javax.swing.JToggleButton();
    jToggleButtonHangUp1 = new javax.swing.JToggleButton();
    jToggleButton1 = new javax.swing.JToggleButton();

    setPreferredSize(new java.awt.Dimension(1595, 150));
    setLayout(new java.awt.GridLayout(1, 2));

    jPanelEHP.setLayout(new java.awt.BorderLayout());

    jPanelEhpTable.setBorder(javax.swing.BorderFactory.createTitledBorder("EHP"));
    jPanelEhpTable.setLayout(new java.awt.BorderLayout());

    jPanelEhpCalls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    jTextField1.setText("Calls ");
    jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
    jPanelEhpCalls.add(jTextField1);

    jPanelEhpTable.add(jPanelEhpCalls, java.awt.BorderLayout.NORTH);

    jPanelEhpTableList.setLayout(new java.awt.BorderLayout());

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3"
      }
    ));
    jScrollPaneEhpTableList.setViewportView(jTable1);
    jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
    jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
    jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");

    jPanelEhpTableList.add(jScrollPaneEhpTableList, java.awt.BorderLayout.CENTER);

    jPanelEhpTable.add(jPanelEhpTableList, java.awt.BorderLayout.CENTER);

    jPanelEHP.add(jPanelEhpTable, java.awt.BorderLayout.CENTER);

    jPanelEhpButtons.setLayout(new java.awt.GridLayout(2, 1));

    jToggleButtonConnect.setText("Connect");
    jToggleButtonConnect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButtonConnectActionPerformed(evt);
      }
    });
    jPanelEhpButtons.add(jToggleButtonConnect);

    jToggleButtonHangUp.setText("Hang-Up");
    jPanelEhpButtons.add(jToggleButtonHangUp);

    jPanelEHP.add(jPanelEhpButtons, java.awt.BorderLayout.EAST);

    add(jPanelEHP);

    jPanelEHP1.setLayout(new java.awt.BorderLayout());

    jPanelEhpTable1.setBorder(javax.swing.BorderFactory.createTitledBorder("Radio"));
    jPanelEhpTable1.setLayout(new java.awt.BorderLayout());

    jPanelEhpCalls1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    jTextField2.setText("Calls ");
    jTextField2.setPreferredSize(new java.awt.Dimension(100, 20));
    jPanelEhpCalls1.add(jTextField2);

    jPanelEhpTable1.add(jPanelEhpCalls1, java.awt.BorderLayout.NORTH);

    jPanelEhpTableList1.setLayout(new java.awt.BorderLayout());

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3"
      }
    ));
    jScrollPaneEhpTableList1.setViewportView(jTable2);
    jTable2.getColumnModel().getColumn(0).setHeaderValue("Title 1");
    jTable2.getColumnModel().getColumn(1).setHeaderValue("Title 2");
    jTable2.getColumnModel().getColumn(2).setHeaderValue("Title 3");

    jPanelEhpTableList1.add(jScrollPaneEhpTableList1, java.awt.BorderLayout.CENTER);

    jPanelEhpTable1.add(jPanelEhpTableList1, java.awt.BorderLayout.CENTER);

    jPanelEHP1.add(jPanelEhpTable1, java.awt.BorderLayout.CENTER);

    jPanelEhpButtons1.setLayout(new java.awt.GridLayout(3, 1));

    jToggleButtonConnect1.setText("Emergency");
    jPanelEhpButtons1.add(jToggleButtonConnect1);

    jToggleButtonHangUp1.setText("Group");
    jPanelEhpButtons1.add(jToggleButtonHangUp1);

    jToggleButton1.setText("Private");
    jPanelEhpButtons1.add(jToggleButton1);

    jPanelEHP1.add(jPanelEhpButtons1, java.awt.BorderLayout.EAST);

    add(jPanelEHP1);
  }// </editor-fold>//GEN-END:initComponents

  private void jToggleButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConnectActionPerformed
    // TODO add your handling code here:

    System.out.println(this.getSize().width+","+this.getSize().height);
  }//GEN-LAST:event_jToggleButtonConnectActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanelEHP;
  private javax.swing.JPanel jPanelEHP1;
  private javax.swing.JPanel jPanelEhpButtons;
  private javax.swing.JPanel jPanelEhpButtons1;
  private javax.swing.JPanel jPanelEhpCalls;
  private javax.swing.JPanel jPanelEhpCalls1;
  private javax.swing.JPanel jPanelEhpTable;
  private javax.swing.JPanel jPanelEhpTable1;
  private javax.swing.JPanel jPanelEhpTableList;
  private javax.swing.JPanel jPanelEhpTableList1;
  private javax.swing.JScrollPane jScrollPaneEhpTableList;
  private javax.swing.JScrollPane jScrollPaneEhpTableList1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTable jTable2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButtonConnect;
  private javax.swing.JToggleButton jToggleButtonConnect1;
  private javax.swing.JToggleButton jToggleButtonHangUp;
  private javax.swing.JToggleButton jToggleButtonHangUp1;
  // End of variables declaration//GEN-END:variables

 /**
  * Returns this class description in a friendly way.
  *
  * @return String description
  */
  public String toString(){
    return new StringBuffer("RadioTlcSpecUpperPanel").append("").toString();
  }

  public static void main(final String[] args){
    final RadioTlcSpecUpperPanel clazz = new RadioTlcSpecUpperPanel();
    final javax.swing.JFrame f = new javax.swing.JFrame();
    f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    f.getContentPane().setLayout(new java.awt.BorderLayout());
    f.getContentPane().add(clazz, java.awt.BorderLayout.CENTER);
    f.pack();
    f.setVisible(true);
  }

}
