/*
 * JPanelTestForNamingJPanels.java
 *
 * Created on 24 de Julho de 2008, 16:18
 */

package jdk1_6examples.javax.swing.jpanel;

/**
 *
 * @author  c2334
 */
public class JPanelTestForNamingJPanels extends javax.swing.JPanel {

    /** Creates new form JPanelTestForNamingJPanels */
    public JPanelTestForNamingJPanels() {
        initComponents();
        
        System.out.println("JPanel name:"+this.getName()+"."); 
        this.setName("AHAHAH");
        System.out.println("JPanel name:"+this.getName()+"."); 
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
      new JPanelTestForNamingJPanels();
    }
}
