/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java22;

public class App {
    public String getGreeting() {
        return "H e l l o    W o r l d!";
    }

    public static void main(String[] args) {
        
      PatternMatchingForSwitch.main(args);

        //.main(args);
      
      RecordsWithInlineClasses.main(args);
      
    }
}
