/*
 * IGSysManApp.java
 *
 * Created on 30 de Novembro de 2007, 14:45
 */

package pt.efacec.igsysman;

/**
 *
 * @author  lmorgado
 * @version
 */

// JAVA imports
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ResourceBundle;

// ENT/Efacec imports
//import com.ent.PInt.GIs.*;
//import com.ent.PInt.GIAccess.GIAccessComponent;
//import com.ent.PInt.PInt;
//import com.ent.corba.EventService.*;
//
public class IGSysManApp 
//    extends GraphicInterfaceApplication implements GIInterface
{

//  private static JMenuBar menuBar = new JMenuBar();
//  private static JToolBar toolbar = new JToolBar();
//  // my application id
//  protected static int myAppID = -1;
//  // permissions currently suported in Inoss:
//  private static final int APP_ACCESS_ADMIN = 1;
//  private static final int APP_ACCESS_MANAG = 2;
//  private static final int APP_ACCESS_OPERAT = 3;
//  // by default, minimum permission
//  private static int appAccess = APP_ACCESS_OPERAT; /** Current GUI Access */
//
//  /** Creates new IGSysManApp */
//  public IGSysManApp() {
//  }
//
//  public IGSysManApp(JInternalFrame frame) {
//  }
//
//  /**  Method that will be used to show the GI. */
//  public void initGI(GIAccessComponent GIAC, JPanel panel, int serverID) {
//    //super.setTitle( GIAC.getGIName() );
//    // gets my app id
//    myAppID = GIAC.getGIId();
//    // gets current user permissions
//    try {
//        appAccess = Integer.parseInt(GIAC.getGIAccess());
//    } catch (Exception e) {
//        appAccess = APP_ACCESS_OPERAT; /*minimum permission*/
//    }
//    initialize(panel);
//    super.initGI(GIAC, panel, serverID);
//  }
//
//  protected void initialize(JPanel treePanel) {
//    // all initializations come here...
//    treePanel.setLayout(new BorderLayout());
//    JTabbedPane tabbedPane = new JTabbedPane();
//    tabbedPane.setFont(new java.awt.Font("SansSerif",
//                                         java.awt.Font.PLAIN, 12));
//    tabbedPane.addTab("teste", null, new JPanel(), "teste");
//    treePanel.add(new JTabbedPane(), BorderLayout.CENTER);
//  }
//
//  public JMenuBar getGIJMenuBar() {
//    return menuBar;
//  }
//
//  public JToolBar getGIJToolBar() {
//    return toolbar;
//  }
//
//  /**
//   * Process the events generated by Server Application
//   */
//  public boolean deliverEvent(Property properties[],
//                              final long relatedEventsList[],
//                              byte specificInfo[]) {
//    return true;
//  }
//
//  public void disableFrame(){
//  }
//
//  public void giveFocus() {
//    super.giveFocus();
//  }
//
//  public void getVersions() { /* para implementar mais tarde... */}
//
//  public void setXML(java.io.InputStream inputStream) {}
//
}
