/*
 * TestingMatisseAgainstJDK16.java
 *
 * Created on 10 de Setembro de 2008, 18:57
 */

package jdk1_6examples.javax.swing.jframe;

/**
 *
 * @author  c2334
 */
public class TestingMatisseAgainstJDK16 extends javax.swing.JFrame {

    /** Creates new form TestingMatisseAgainstJDK16 */
    public TestingMatisseAgainstJDK16() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingMatisseAgainstJDK16().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
