/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 28/Set/2010, 18:19:40
 */

package tlc;

/**
 *
 * @author 2334
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelDBSID = new javax.swing.JLabel();
    jTextFieldDBSID = new javax.swing.JTextField();
    jLabelDBName = new javax.swing.JLabel();
    jTextFieldDBName = new javax.swing.JTextField();
    jTextFieldDBType = new javax.swing.JTextField();
    jLabelDBType = new javax.swing.JLabel();
    jLabelDBVersion = new javax.swing.JLabel();
    jTextFieldDBVersion = new javax.swing.JTextField();

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tlc/Bundle"); // NOI18N
    jLabelDBSID.setText(bundle.getString("NewJPanel.jLabelDBSID.text")); // NOI18N

    jTextFieldDBSID.setText(bundle.getString("NewJPanel.jTextFieldDBSID.text")); // NOI18N

    jLabelDBName.setText(bundle.getString("NewJPanel.jLabelDBName.text")); // NOI18N

    jTextFieldDBName.setText(bundle.getString("NewJPanel.jTextFieldDBName.text")); // NOI18N

    jTextFieldDBType.setText(bundle.getString("NewJPanel.jTextFieldDBType.text")); // NOI18N

    jLabelDBType.setText(bundle.getString("NewJPanel.jLabelDBType.text")); // NOI18N

    jLabelDBVersion.setText(bundle.getString("NewJPanel.jLabelDBVersion.text")); // NOI18N

    jTextFieldDBVersion.setText(bundle.getString("NewJPanel.jTextFieldDBVersion.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelDBSID)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldDBSID, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelDBName)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelDBType)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldDBType, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelDBVersion)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldDBVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(37, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDBSID)
          .addComponent(jTextFieldDBSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDBName)
          .addComponent(jTextFieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDBType)
          .addComponent(jTextFieldDBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDBVersion)
          .addComponent(jTextFieldDBVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(191, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabelDBName;
  private javax.swing.JLabel jLabelDBSID;
  private javax.swing.JLabel jLabelDBType;
  private javax.swing.JLabel jLabelDBVersion;
  private javax.swing.JTextField jTextFieldDBName;
  private javax.swing.JTextField jTextFieldDBSID;
  private javax.swing.JTextField jTextFieldDBType;
  private javax.swing.JTextField jTextFieldDBVersion;
  // End of variables declaration//GEN-END:variables

}
