/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TlcMainFrameTests.java
 *
 * Created on 5/Dez/2008, 11:30:29
 */

package tlc;

/**
 *
 * @author c2334
 */
public class TlcMainFrameTests extends javax.swing.JFrame {

    /** Creates new form TlcMainFrameTests */
    public TlcMainFrameTests() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelToolbar = new javax.swing.JPanel();
    jPanelEvtsComm = new javax.swing.JPanel();
    jPanelMain = new javax.swing.JPanel();
    jPanelSpecUpperArea = new javax.swing.JPanel();
    jPanelTrees = new javax.swing.JPanel();
    jPanelMaps = new javax.swing.JPanel();
    jPanelSpecArea = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelToolbar.setPreferredSize(new java.awt.Dimension(1000, 50));

    javax.swing.GroupLayout jPanelToolbarLayout = new javax.swing.GroupLayout(jPanelToolbar);
    jPanelToolbar.setLayout(jPanelToolbarLayout);
    jPanelToolbarLayout.setHorizontalGroup(
      jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 735, Short.MAX_VALUE)
    );
    jPanelToolbarLayout.setVerticalGroup(
      jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 50, Short.MAX_VALUE)
    );

    getContentPane().add(jPanelToolbar, java.awt.BorderLayout.PAGE_START);

    jPanelEvtsComm.setPreferredSize(new java.awt.Dimension(735, 150));

    javax.swing.GroupLayout jPanelEvtsCommLayout = new javax.swing.GroupLayout(jPanelEvtsComm);
    jPanelEvtsComm.setLayout(jPanelEvtsCommLayout);
    jPanelEvtsCommLayout.setHorizontalGroup(
      jPanelEvtsCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 735, Short.MAX_VALUE)
    );
    jPanelEvtsCommLayout.setVerticalGroup(
      jPanelEvtsCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 150, Short.MAX_VALUE)
    );

    getContentPane().add(jPanelEvtsComm, java.awt.BorderLayout.PAGE_END);

    jPanelMain.setLayout(null);

    jPanelSpecUpperArea.setBackground(new java.awt.Color(153, 255, 255));

    javax.swing.GroupLayout jPanelSpecUpperAreaLayout = new javax.swing.GroupLayout(jPanelSpecUpperArea);
    jPanelSpecUpperArea.setLayout(jPanelSpecUpperAreaLayout);
    jPanelSpecUpperAreaLayout.setHorizontalGroup(
      jPanelSpecUpperAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 700, Short.MAX_VALUE)
    );
    jPanelSpecUpperAreaLayout.setVerticalGroup(
      jPanelSpecUpperAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    jPanelMain.add(jPanelSpecUpperArea);
    jPanelSpecUpperArea.setBounds(0, 0, 700, 100);

    jPanelTrees.setBackground(new java.awt.Color(51, 204, 0));

    javax.swing.GroupLayout jPanelTreesLayout = new javax.swing.GroupLayout(jPanelTrees);
    jPanelTrees.setLayout(jPanelTreesLayout);
    jPanelTreesLayout.setHorizontalGroup(
      jPanelTreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 140, Short.MAX_VALUE)
    );
    jPanelTreesLayout.setVerticalGroup(
      jPanelTreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    jPanelMain.add(jPanelTrees);
    jPanelTrees.setBounds(10, 110, 140, 430);

    jPanelMaps.setBackground(new java.awt.Color(255, 102, 102));

    javax.swing.GroupLayout jPanelMapsLayout = new javax.swing.GroupLayout(jPanelMaps);
    jPanelMaps.setLayout(jPanelMapsLayout);
    jPanelMapsLayout.setHorizontalGroup(
      jPanelMapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 470, Short.MAX_VALUE)
    );
    jPanelMapsLayout.setVerticalGroup(
      jPanelMapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    jPanelMain.add(jPanelMaps);
    jPanelMaps.setBounds(170, 110, 470, 430);

    jPanelSpecArea.setBackground(new java.awt.Color(153, 0, 153));

    javax.swing.GroupLayout jPanelSpecAreaLayout = new javax.swing.GroupLayout(jPanelSpecArea);
    jPanelSpecArea.setLayout(jPanelSpecAreaLayout);
    jPanelSpecAreaLayout.setHorizontalGroup(
      jPanelSpecAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 80, Short.MAX_VALUE)
    );
    jPanelSpecAreaLayout.setVerticalGroup(
      jPanelSpecAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    jPanelMain.add(jPanelSpecArea);
    jPanelSpecArea.setBounds(650, 110, 80, 430);

    getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TlcMainFrameTests().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanelEvtsComm;
  private javax.swing.JPanel jPanelMain;
  private javax.swing.JPanel jPanelMaps;
  private javax.swing.JPanel jPanelSpecArea;
  private javax.swing.JPanel jPanelSpecUpperArea;
  private javax.swing.JPanel jPanelToolbar;
  private javax.swing.JPanel jPanelTrees;
  // End of variables declaration//GEN-END:variables

}
