/*
 * NewStationsAddition.java
 *
 * Created on 25 de Julho de 2008, 15:22
 */

package jdk1_6examples.inoss.tests.station.add;

/**
 *
 * @author  c2334
 */
public class NewStationsAddition extends javax.swing.JFrame {

    /** Creates new form NewStationsAddition */
    public NewStationsAddition() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton3 = new javax.swing.JRadioButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jCheckBox1 = new javax.swing.JCheckBox();
    jPanel8 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();
    jPanel9 = new javax.swing.JPanel();
    jCheckBox2 = new javax.swing.JCheckBox();
    jPanel10 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Stations");

    jRadioButton1.setSelected(true);
    jRadioButton1.setText("Add");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jRadioButton1);

    jRadioButton2.setText("Edit");
    jPanel1.add(jRadioButton2);

    jRadioButton3.setText("Remove");
    jPanel1.add(jRadioButton3);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
    jPanel2.setLayout(new java.awt.GridLayout(3, 2));

    jLabel1.setText("Name:");
    jPanel2.add(jLabel1);

    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });
    jPanel2.add(jTextField1);

    jLabel2.setText("Abbreviated name:");
    jPanel2.add(jLabel2);
    jPanel2.add(jTextField2);

    jLabel3.setText("...");
    jPanel2.add(jLabel3);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modules Specific Configurations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
    jPanel3.setLayout(new java.awt.BorderLayout());

    jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    jButton2.setText("Add");
    jPanel4.add(jButton2);

    jButton1.setText("Exit");
    jPanel4.add(jButton1);

    jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

    jPanel5.setLayout(new java.awt.GridLayout(2, 0));

    jPanel7.setLayout(new java.awt.BorderLayout());

    jCheckBox1.setSelected(true);
    jCheckBox1.setText("CCTV");
    jPanel7.add(jCheckBox1, java.awt.BorderLayout.CENTER);

    jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
    jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel4.setText("Agent:");
    jPanel8.add(jLabel4);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
    jPanel8.add(jComboBox1);

    jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

    jPanel5.add(jPanel7);

    jPanel9.setLayout(new java.awt.BorderLayout());

    jCheckBox2.setText("PA");
    jPanel9.add(jCheckBox2, java.awt.BorderLayout.CENTER);

    jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
    jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel5.setText("Agent:");
    jPanel10.add(jLabel5);

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox2.setEnabled(false);
    jComboBox2.setPreferredSize(new java.awt.Dimension(150, 22));
    jPanel10.add(jComboBox2);

    jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_END);

    jPanel5.add(jPanel9);

    jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

    getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStationsAddition().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  // End of variables declaration//GEN-END:variables

}
