/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyCompsBorder.java
 *
 * Created on 11/Fev/2009, 10:44:45
 */

package jdk1_6examples.javax.swing.border;

/**
 *
 * @author c2334
 */
public class MyCompsBorder extends javax.swing.JFrame {

    /** Creates new form MyCompsBorder */
    public MyCompsBorder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(null);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 320, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 110, Short.MAX_VALUE)
    );

    getContentPane().add(jPanel1);
    jPanel1.setBounds(50, 100, 320, 110);

    jRadioButton1.setText("jRadioButton1");
    getContentPane().add(jRadioButton1);
    jRadioButton1.setBounds(70, 250, 93, 23);

    jRadioButton2.setText("jRadioButton2");
    getContentPane().add(jRadioButton2);
    jRadioButton2.setBounds(200, 260, 93, 23);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCompsBorder().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  // End of variables declaration//GEN-END:variables

}
