/*
 * VeryLongDescTabs.java
 *
 * Created on 12 de Junho de 2008, 11:59
 */

package exp.swing.jtabbedpane;

import java.awt.BorderLayout;
import javax.swing.JFrame;

import javax.swing.GroupLayout.Alignment;


/**
 *
 * @author  C2334
 */
public class VeryLongDescTabs extends javax.swing.JPanel {

    /** Creates new form VeryLongDescTabs */
    public VeryLongDescTabs() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    jPanel9 = new javax.swing.JPanel();
    jPanel10 = new javax.swing.JPanel();
    jPanel11 = new javax.swing.JPanel();

    setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Camera Selection", jPanel1);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Camera Selection", jPanel2);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Sequence Execution", jPanel3);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Replay Video Recording", jPanel4);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Start Recording", jPanel5);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Stop Recording/Replay", jPanel6);

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Enable/Disable Actuator", jPanel7);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Pause Macro Execution", jPanel8);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Modify Stop State", jPanel9);

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
      jPanel10Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel10Layout.setVerticalGroup(
      jPanel10Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Disconnect Video ", jPanel10);

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
      jPanel11Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 395, Short.MAX_VALUE)
    );
    jPanel11Layout.setVerticalGroup(
      jPanel11Layout.createParallelGroup(Alignment.LEADING)
      .addGap(0, 275, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Tag Recording as in Alarm", jPanel11);

    add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel11;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JTabbedPane jTabbedPane1;
  // End of variables declaration//GEN-END:variables

  
  public static void main(String[] args) {
    JFrame f = new JFrame("Macros");
    f.getContentPane().setLayout(new BorderLayout());
    f.getContentPane().add(new VeryLongDescTabs());
    f.setBounds(100,100,450,300);
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setVisible(true);
  }
}
